import express from"express";import fs from"fs/promises";import path from"path";import crypto from"crypto";
const app=express(),PORT=process.env.PORT||8080,ROOT=process.env.DATA_DIR||"./data",DB=path.join(ROOT,"steamdb"),CUR=path.join(DB,"current.json"),ST=path.join(DB,"state.json"),SET=path.join(DB,"settings.json"),OBJ=path.join(DB,"objects"),COM=path.join(DB,"commits"),STORE_URL="https://partner."+"steam-api.com/IStoreService/GetAppList/v1/";
app.use(express.json({limit:"1mb"}));app.use(express.static("public"));
async function rj(f,d){try{return JSON.parse(await fs.readFile(f,"utf8"))}catch{return d}}async function wj(f,d){await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f,JSON.stringify(d,null,2))}const sh=x=>crypto.createHash("sha1").update(JSON.stringify(x)).digest("hex"),mask=k=>k?k.slice(0,4)+"..."+k.slice(-4):null;
async function key(){let s=await rj(SET,{});return s.k||process.env.STEAM_API_KEY||""}
async function pag(k,last=0){let input={include_games:true,include_dlc:true,include_software:true,last_appid:last,max_results:50000};let u=new globalThis.URL(STORE_URL);u.searchParams.set("key",k);u.searchParams.set("format","json");u.searchParams.set("input_json",JSON.stringify(input));let res=await fetch(u),txt=await res.text(),j;try{j=JSON.parse(txt)}catch{j={raw:txt.slice(0,300)}}if(!res.ok)throw Error("Steam HTTP "+res.status+": "+JSON.stringify(j).slice(0,300));return j.response||j}
async function fetchApps(){let k=await key();if(!k)throw Error("Steam API key is not saved");let all=[],seen=new Set,last=0;for(let i=0;i<50;i++){let p=await pag(k,last),a=p.apps||[];if(!a.length)break;let m=last;for(let x of a){let appid=+x.appid,name=String(x.name||"").trim();if(!appid||!name||seen.has(appid))continue;seen.add(appid);all.push({appid,name,type:x.type||null,last_modified:x.last_modified||null});if(appid>m)m=appid}if(p.have_more_results===false||m===last)break;last=m}return all.sort((a,b)=>a.appid-b.appid)}
function diff(a,b){let p=new Map(a.map(x=>[x.appid,x])),n=new Map(b.map(x=>[x.appid,x])),added=[],removed=[],renamed=[];for(let x of b){let o=p.get(x.appid);if(!o)added.push(x);else if(o.name!==x.name)renamed.push({appid:x.appid,oldName:o.name,newName:x.name})}for(let x of a)if(!n.has(x.appid))removed.push(x);return{added,removed,renamed}}let running=false,lastSync=null,lastError=null;
async function sync(reason="manual"){if(running)return{ok:false,running:true};running=true;try{await fs.mkdir(OBJ,{recursive:true});await fs.mkdir(COM,{recursive:true});let apps=await fetchApps(),object=sh(apps),st=await rj(ST,{head:null,commits:[]}),prev=st.head?await rj(path.join(OBJ,st.head+".json"),[]):[],d=diff(prev,apps),changed=st.head!==object,commit=null;await wj(path.join(OBJ,object+".json"),apps);await wj(CUR,apps);if(changed){commit={id:crypto.randomUUID(),object,parent:st.head,createdAt:new Date().toISOString(),reason,total:apps.length,diff:{added:d.added.length,removed:d.removed.length,renamed:d.renamed.length}};await wj(path.join(COM,commit.id+".json"),commit);await wj(ST,{head:object,updatedAt:commit.createdAt,commits:[commit.id,...(st.commits||[])].slice(0,2000)})}lastSync={at:new Date().toISOString(),reason,changed,total:apps.length};lastError=null;return{ok:true,changed,commit,total:apps.length,diff:d}}catch(e){lastError={at:new Date().toISOString(),message:e.message};throw e}finally{running=false}}
setInterval(()=>sync("hourly").catch(e=>console.error(e.message)),3600000);setTimeout(()=>sync("startup").catch(e=>console.error(e.message)),1500);
app.get("/health",(q,s)=>s.json({ok:true,app:"blaze-steam-gitdb"}));app.get("/api/settings",async(q,s)=>{let k=await key();s.json({ok:true,steamApiKeySaved:!!k,steamApiKeyMasked:mask(k)})});app.post("/api/settings",async(q,s)=>{let k=String(q.body?.steamApiKey||"").trim();if(!k)return s.status(400).json({ok:false,error:"steamApiKey required"});await wj(SET,{k,updatedAt:new Date().toISOString()});s.json({ok:true,steamApiKeyMasked:mask(k)})});
app.get("/api/status",async(q,s)=>{let st=await rj(ST,{head:null,commits:[]}),a=await rj(CUR,[]),k=await key();s.json({ok:true,total:a.length,head:st.head,commits:(st.commits||[]).length,updatedAt:st.updatedAt||null,running,lastSync,lastError,steamApiKeySaved:!!k,steamApiKeyMasked:mask(k)})});app.post("/api/sync",async(q,s)=>{try{s.json(await sync())}catch(e){s.status(500).json({ok:false,error:e.message})}});app.get("/api/apps",async(q,s)=>{let a=await rj(CUR,[]),qq=String(q.query.q||"").toLowerCase(),lim=Math.min(+q.query.limit||100,1000);if(qq)a=a.filter(x=>String(x.appid).includes(qq)||x.name.toLowerCase().includes(qq));s.json({ok:true,total:a.length,apps:a.slice(0,lim)})});app.get("/api/commits",async(q,s)=>{let st=await rj(ST,{commits:[]}),out=[];for(let id of(st.commits||[]).slice(0,+q.query.limit||50)){let c=await rj(path.join(COM,id+".json"),null);if(c)out.push(c)}s.json({ok:true,commits:out})});app.listen(PORT,()=>console.log("Blaze Steam GitDB on "+PORT));